CREATE TABLE "Pod" (
  "id" TEXT NOT NULL,
  "sessionId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  CONSTRAINT "Pod_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Pod" ADD CONSTRAINT "Pod_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SessionPlayer" ADD COLUMN "podId" TEXT;
ALTER TABLE "SessionPlayer" ADD CONSTRAINT "SessionPlayer_podId_fkey" FOREIGN KEY ("podId") REFERENCES "Pod"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Team" ADD COLUMN "podId" TEXT;
ALTER TABLE "Team" ADD CONSTRAINT "Team_podId_fkey" FOREIGN KEY ("podId") REFERENCES "Pod"("id") ON DELETE SET NULL ON UPDATE CASCADE;
